# This is a basic workflow to help you get started with Actions

name: Gif Comment
on: 
  issues:
    types: [opened]
    
jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latet
    steps:
      - name: add funny comment
        uses: leeorn/funny-commet-action@v2.1
        id: funnyComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }} 
#           GIPHY_TOKEN: ${{ 65QHew199v03lWFno95U1yODCSjBtMCZ }}
          comment_type: 'gif'
    
